# Generated by Django 4.2.9 on 2026-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('BP', 'British Parliamentary'), ('WSDC', 'WSDC')], default='BP', max_length=10)),
                ('num_prelim_rounds', models.IntegerField(default=5)),
                ('num_break_rounds', models.IntegerField(default=2)),
                ('break_size', models.IntegerField(default=8)),
                ('motions_public', models.BooleanField(default=False)),
                ('tab_released', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
