# Generated by Django 4.2.9 on 2026-02-28 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjudicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('base_score', models.FloatField(default=75.0)),
                ('independent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-base_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdjudicatorConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('personal', 'Personal'), ('institution', 'Institutional')], default='personal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdjudicatorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='adjudication.adjudicator')),
            ],
        ),
    ]
