# Generated by Django 4.2.9 on 2026-02-28 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adjudication', '0001_initial'),
        ('participants', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('draws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draws.debate'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='source_adjudicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to='adjudication.adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='adjudication.adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorconflict',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.team'),
        ),
        migrations.AddField(
            model_name='adjudicator',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.institution'),
        ),
        migrations.AddField(
            model_name='adjudicator',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicators', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='adjudicator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
