# Generated by Django 4.2.9 on 2026-02-28 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjudication', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cg_debates', to='participants.team')),
                ('co_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_debates', to='participants.team')),
                ('og_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='og_debates', to='participants.team')),
                ('oo_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oo_debates', to='participants.team')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('draw_type', models.CharField(choices=[('random', 'Random'), ('power', 'Power Paired'), ('elim', 'Elimination')], default='random', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='draft', max_length=20)),
                ('motion', models.TextField(blank=True)),
                ('info_slide', models.TextField(blank=True)),
                ('is_break_round', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('tournament', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DebateAdjudicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_type', models.CharField(choices=[('chair', 'Chair'), ('panelist', 'Panelist'), ('trainee', 'Trainee')], default='panelist', max_length=20)),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjudication.adjudicator')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_adjudicators', to='draws.debate')),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='draws.room'),
        ),
        migrations.AddField(
            model_name='debate',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='draws.round'),
        ),
    ]
